/**
 * 1000 common GASCOIN questions — generated from every page, doc section,
 * gate, and user scenario on the platform.
 *
 * Categories:
 *   Getting started (80), Receipts (90), Tweets (70), Gates 1-17 (170),
 *   Tiers & tokens (70), Cooldowns (50), Payouts (70), Points & streaks (60),
 *   Referrals (50), Troubleshooting (100), Security & privacy (40),
 *   Platform pages (50), Crypto basics (40), Comparisons (30), Edge cases (30)
 */

export const QUESTIONS_1000: string[] = [
  // ════════════════════════════════════════════════════════════════════════════
  // GETTING STARTED (80)
  // ════════════════════════════════════════════════════════════════════════════
  'how does gascoin work',
  'what is gascoin in simple terms',
  'explain gascoin to me like I\'m five',
  'how do I get started',
  'what do I need before I can submit',
  'is gascoin free to use',
  'do I need crypto experience',
  'how do I create a solana wallet',
  'what wallets are supported',
  'can I use metamask',
  'can I use coinbase wallet',
  'can I use trust wallet',
  'how do I install phantom',
  'how do I install solflare',
  'how do I install backpack wallet',
  'what is a wallet address',
  'where do I find my wallet address',
  'what is a seed phrase and why does it matter',
  'can you walk me through the whole process',
  'what are all the requirements',
  'do I need a verified twitter account',
  'do I need followers on twitter',
  'how old does my twitter account need to be',
  'what if I don\'t have x premium',
  'what is an invite code',
  'where do I get an invite code',
  'what format is the invite code',
  'can I use gascoin without an invite code',
  'is season 1 still active',
  'what is season 1 beta',
  'when did gascoin launch',
  'what happens after season 1',
  'is there a mobile app',
  'does gascoin work on iphone',
  'does gascoin work on android',
  'can I use gascoin on my computer',
  'which browser works best',
  'do I need to download anything',
  'how long does the whole process take',
  'how many steps are there',
  'what is the first thing I should do',
  'what is the submission portal',
  'where do I submit my receipt',
  'what is gascoin.app/submit',
  'do I need to sign in',
  'how do I sign in with twitter',
  'what is privy login',
  'can I submit without signing in',
  'what happens after I connect my wallet',
  'can I change my wallet after connecting',
  'can I use multiple wallets',
  'can I use the same wallet for multiple x accounts',
  'is there a video tutorial',
  'is there a guide on the website',
  'where is the documentation',
  'what is gascoin.app/how-it-works',
  'what is the how it works page',
  'how many submissions have been processed',
  'how many users does gascoin have',
  'what countries is gascoin available in',
  'does gascoin work outside the us',
  'can I use gascoin in canada',
  'can I use gascoin in europe',
  'can I use gascoin in mexico',
  'can I use gascoin in south america',
  'can I use gascoin in asia',
  'can I use gascoin in africa',
  'does my currency matter',
  'how does currency conversion work',
  'what currencies are accepted',
  'do I need a us gas station',
  'does any gas station work',
  'can I use costco gas station',
  'can I use shell gas station',
  'can I use bp gas station',
  'can I use a small local gas station',
  'what gas stations are not accepted',
  'does the gas station brand matter',
  'is there a list of approved stations',
  'how do I know if my station qualifies',

  // ════════════════════════════════════════════════════════════════════════════
  // RECEIPTS (90)
  // ════════════════════════════════════════════════════════════════════════════
  'what kind of receipt do I need',
  'does it have to be a paper receipt',
  'can I use a digital receipt',
  'can I use an email receipt',
  'can I use a screenshot of a receipt',
  'what if my receipt is from a credit card app',
  'can I use apple pay receipt',
  'what information must be on the receipt',
  'does the receipt need to show the date',
  'does the receipt need to show the total',
  'does the receipt need to show gallons',
  'does the receipt need to show price per gallon',
  'does the receipt need the station name',
  'does the receipt need the station address',
  'what if my receipt doesn\'t show gallons',
  'what if my receipt only shows liters',
  'what is the minimum receipt amount',
  'what if my receipt is under five dollars',
  'how old can my receipt be',
  'can I use a receipt from two weeks ago',
  'can I use a receipt from yesterday',
  'what if my receipt is from exactly 7 days ago',
  'what do I write on the receipt',
  'where should I write on the receipt',
  'what pen should I use',
  'can I use a pencil',
  'can I use a marker',
  'how big should I write',
  'what are the last 4 characters of my wallet',
  'where do I find my last 4 wallet characters',
  'what if I write the wrong wallet characters',
  'do I also need to write the hashtag on the receipt',
  'why do I need to write on the physical receipt',
  'what if I write gascoin without the hashtag',
  'can I write on the back of the receipt',
  'can I write in the margins',
  'what if the receipt is too small to write on',
  'what if my handwriting is messy',
  'how do I take a good photo of the receipt',
  'should I use flash',
  'what angle should I photograph the receipt',
  'does the whole receipt need to be visible',
  'can I crop the photo',
  'can I edit the brightness of the photo',
  'can I use a filter on the photo',
  'what resolution does the photo need to be',
  'can I scan the receipt instead',
  'what if my receipt is faded',
  'what if my receipt got wet',
  'what if my receipt is crumpled',
  'can I tape a torn receipt',
  'what if my receipt has coffee stains',
  'what if part of the receipt is cut off',
  'can I use a receipt from a grocery store gas pump',
  'does the receipt need to say gasoline specifically',
  'what if my receipt says fuel instead of gasoline',
  'can I use a diesel receipt',
  'can I use an ev charging receipt',
  'can I use a car wash receipt',
  'what if my receipt includes a car wash charge',
  'what if I bought snacks along with gas',
  'does the receipt need to only be for gas',
  'what if I have multiple items on the receipt',
  'can I use a receipt from a pay at pump',
  'what if the receipt printed twice',
  'can I use the credit card copy of the receipt',
  'what if I lost my receipt after submitting',
  'can I submit two receipts at once',
  'how many receipts can I submit per week',
  'can I save a receipt for later',
  'what happens to my receipt after review',
  'does gascoin store my receipt permanently',
  'when does gascoin delete my receipt data',
  'what format should the photo be',
  'can I upload a pdf receipt',
  'what is the max file size for the upload',
  'can I take the photo with my phone camera',
  'is it better to photograph in portrait or landscape',
  'what lighting works best for receipt photos',
  'should I place the receipt on a specific surface',
  'what color surface is best for photographing receipts',
  'can I photograph my receipt on a dark surface',
  'what if the flash creates glare on the receipt',
  'do thermal receipts work better than ink receipts',
  'what if my receipt faded because it\'s thermal paper',
  'can I photograph the receipt through glass',
  'what if my receipt is in another language',
  'does the receipt language matter',
  'can I submit a handwritten receipt',

  // ════════════════════════════════════════════════════════════════════════════
  // TWEETS (70)
  // ════════════════════════════════════════════════════════════════════════════
  'what should my tweet say',
  'what is the exact tweet format',
  'do I need to include a hashtag',
  'do I need to include a cashtag',
  'what is the difference between hashtag and cashtag',
  'is it #gascoin or #GASCOIN',
  'does capitalization matter for the hashtag',
  'do I need to tag gazcoinapp',
  'what if I misspell gazcoinapp',
  'what if I tag gascoin instead of gazcoinapp',
  'does the tweet need to include a photo',
  'does the receipt photo go in the tweet',
  'can I use a quote tweet',
  'can I use a reply tweet',
  'can I use a thread',
  'does the tweet need to be the first in a thread',
  'can I include other hashtags',
  'can I include links in my tweet',
  'can I tweet in a different language',
  'does the tweet text need to be in english',
  'what if I tweet in spanish',
  'how long should my tweet be',
  'is there a minimum tweet length',
  'can I just tweet the hashtag and tag with nothing else',
  'example tweet for gascoin',
  'show me a sample tweet',
  'what is a good tweet template',
  'should I pin my gascoin tweet',
  'can my account be private',
  'does my account need to be public',
  'what happens if I go private after tweeting',
  'can I delete the tweet after submitting',
  'when can I safely delete my tweet',
  'can I delete the tweet after receiving sol',
  'what if my tweet gets reported',
  'what if twitter removes my tweet',
  'what if twitter flags my tweet as spam',
  'what if my tweet has a content warning',
  'can I schedule the tweet',
  'can I use a twitter bot to post',
  'does the tweet need to be from my main account',
  'can I use an alt account to tweet',
  'does my x account need to be verified',
  'what kind of verification do I need',
  'does blue check work',
  'does business verification work',
  'does government verification work',
  'what if my x premium expired',
  'how many followers do I need',
  'are bot followers counted',
  'do I need a bio on my profile',
  'what if my account is new',
  'how old does my x account need to be',
  'do I need to follow gazcoinapp',
  'when should I follow gazcoinapp',
  'what if the follow hasn\'t registered yet',
  'how long after following can I submit',
  'can I unfollow after submitting',
  'what if I unfollowed by accident',
  'what is account quality score',
  'how is account quality measured',
  'what improves my account quality',
  'what lowers my account quality',
  'can I have a protected account',
  'what if I have twitter blue but got suspended before',
  'does my follower to following ratio matter',
  'do I need to have posted before',
  'what kind of posting history do I need',
  'can I create a new x account just for gascoin',
  'what tweet url format do I paste',

  // ════════════════════════════════════════════════════════════════════════════
  // GATES 1-17 (170) — 10 questions per gate
  // ════════════════════════════════════════════════════════════════════════════
  // Gate 1 — X Account Verified
  'what is gate 1', 'how do I pass gate 1', 'why did I fail gate 1',
  'what does the x account verified gate check', 'do I need x premium for gate 1',
  'can I pass gate 1 without a blue check', 'what if my verification expired',
  'how do I get verified on x', 'is twitter blue the same as x premium',
  'how much does x premium cost',

  // Gate 2 — Follows @GasCoinApp
  'what is gate 2', 'how do I pass gate 2', 'why did I fail gate 2',
  'what does the follows gate check', 'do I need to follow before submitting',
  'how long after following does gate 2 pass', 'what if gate 2 still fails after following',
  'does unfollowing after submission matter', 'is there a cache delay for following',
  'can I follow from my phone',

  // Gate 3 — Submission Cooldown
  'what is gate 3', 'how do I pass gate 3', 'why did I fail gate 3',
  'what is the submission cooldown', 'how long is my cooldown',
  'is the cooldown per wallet or per account', 'can I reset my cooldown',
  'what if I submitted from a different wallet', 'does the tier affect cooldown',
  'where can I check my cooldown timer',

  // Gate 4 — Min 100 Followers
  'what is gate 4', 'how do I pass gate 4', 'why did I fail gate 4',
  'how many followers do I need exactly', 'do purchased followers count',
  'how does gascoin detect bot followers', 'what if I have 99 followers',
  'do my followers need to be real people', 'can I buy followers to pass',
  'how long after getting 100 followers can I submit',

  // Gate 5 — Account Quality
  'what is gate 5', 'how do I pass gate 5', 'why did I fail gate 5',
  'what factors affect account quality', 'does my bio matter',
  'does my posting history matter', 'how old does my account need to be',
  'what is a good account quality score', 'can I improve my score quickly',
  'what makes an account fail quality check',

  // Gate 6 — Tweet Contains Hashtag
  'what is gate 6', 'how do I pass gate 6', 'why did I fail gate 6',
  'does my tweet need #gascoin or $gascoin', 'is the hashtag case sensitive',
  'what if the hashtag is inside a url', 'can I use both hashtag and cashtag',
  'what if I used #GasCoin with different casing', 'does the cashtag show a price chart',
  'where should the hashtag go in the tweet',

  // Gate 7 — Tweet Tags @GasCoinApp
  'what is gate 7', 'how do I pass gate 7', 'why did I fail gate 7',
  'how do I tag gazcoinapp correctly', 'what if I tag the wrong account',
  'is the tag case sensitive', 'what common typos cause gate 7 to fail',
  'can I tag in a reply instead', 'does the tag need to be in the main text',
  'what if autocomplete changed the tag',

  // Gate 8 — Tweet Is Live
  'what is gate 8', 'how do I pass gate 8', 'why did I fail gate 8',
  'does my tweet need to stay up', 'what if I deleted my tweet by accident',
  'does my account need to be public', 'what if my account is temporarily restricted',
  'how does gascoin check if the tweet exists', 'can I repost the tweet if deleted',
  'what if twitter shows an age gate on my tweet',

  // Gate 9 — Receipt Has #gascoin
  'what is gate 9', 'how do I pass gate 9', 'why did I fail gate 9',
  'do I need to write gascoin on the receipt', 'does it need the hashtag symbol',
  'what if I wrote it too small', 'what if the ocr can\'t read my handwriting',
  'where should I write the hashtag on the receipt', 'what pen color works best',
  'can I print a label and stick it on the receipt',

  // Gate 10 — Wallet Characters on Receipt
  'what is gate 10', 'how do I pass gate 10', 'why did I fail gate 10',
  'what are the last 4 characters of my wallet', 'what if I wrote the wrong characters',
  'how big should I write the characters', 'what if the characters look like other letters',
  'is gate 10 the most common failure', 'tips for passing gate 10',
  'can I write the full wallet address instead of last 4',

  // Gate 11 — Not a Duplicate
  'what is gate 11', 'how do I pass gate 11', 'why did I fail gate 11',
  'can I submit the same receipt twice', 'what if I crop the receipt differently',
  'does rotating the photo bypass duplicate detection', 'how does duplicate detection work',
  'what if I have two similar receipts from different visits', 'can I submit the same gas station twice',
  'does changing brightness bypass the check',

  // Gate 12 — Not AI Generated
  'what is gate 12', 'how do I pass gate 12', 'why did I fail gate 12',
  'how does gascoin detect ai generated images', 'can I use a photo editor',
  'what if I enhanced the photo for clarity', 'does gascoin check exif data',
  'what triggers the ai detection', 'can I use my phone\'s built in photo enhancement',
  'what if the ai detector has a false positive',

  // Gate 13 — Not Tampered
  'what is gate 13', 'how do I pass gate 13', 'why did I fail gate 13',
  'what counts as tampering', 'can I adjust brightness on my receipt photo',
  'what if I accidentally edited something', 'does cropping count as tampering',
  'what tools detect digital manipulation', 'can I add text overlay to the photo',
  'what if my photo app automatically adjusts the image',

  // Gate 14 — Minimum Amount
  'what is gate 14', 'how do I pass gate 14', 'why did I fail gate 14',
  'what is the minimum amount for a receipt', 'is the minimum in usd',
  'what if my receipt is in euros', 'what if the ocr misread the amount',
  'does the amount include tax', 'can I submit a partial fill up',
  'what if I only put in a few dollars of gas',

  // Gate 15 — Receipt Date
  'what is gate 15', 'how do I pass gate 15', 'why did I fail gate 15',
  'how old can my receipt be', 'what if my receipt is exactly 7 days old',
  'what if the date is hard to read', 'does the date need to be in a specific format',
  'what timezone does gascoin use for the date check', 'can I submit a future dated receipt',
  'what if the receipt date is partially obscured',

  // Gate 16 — Amount Verified
  'what is gate 16', 'how do I pass gate 16', 'why did I fail gate 16',
  'what amount should I enter in the form', 'what if the ocr read a different amount',
  'how much tolerance is there', 'should I round the amount up or down',
  'what if I entered the subtotal instead of total', 'does the entered amount include tax',
  'what if my receipt shows multiple amounts',

  // Gate 17 — Token Hold
  'what is gate 17', 'how do I pass gate 17', 'is gate 17 blocking',
  'do I need tokens to submit', 'what happens if I fail gate 17',
  'does gate 17 affect my payout', 'what is the minimum token hold',
  'is gate 17 informational only', 'will gate 17 become blocking in the future',
  'what tier does gate 17 assign me',

  // ════════════════════════════════════════════════════════════════════════════
  // TIERS & TOKENS (70)
  // ════════════════════════════════════════════════════════════════════════════
  'what are the token tiers',
  'how many tiers are there',
  'what is standard tier',
  'what is commuter tier',
  'what is road warrior tier',
  'what is fleet tier',
  'how many tokens for standard tier',
  'how many tokens for commuter tier',
  'how many tokens for road warrior tier',
  'how many tokens for fleet tier',
  'what are the benefits of higher tiers',
  'do higher tiers get bigger refunds',
  'how many submissions per week at each tier',
  'what is the cooldown for each tier',
  'what is the refund cap per tier',
  'are the exact refund amounts published',
  'why aren\'t exact refund amounts published',
  'where do I buy gascoin tokens',
  'how do I buy tokens on jupiter',
  'how do I buy tokens on raydium',
  'what is jupiter jup.ag',
  'what is raydium',
  'can I buy gascoin on coinbase',
  'can I buy gascoin on binance',
  'is gascoin listed on any cex',
  'what is the gascoin token address',
  'what is the gascoin contract address',
  'is gascoin an spl token',
  'what blockchain is gascoin on',
  'what is the total supply of gascoin',
  'what is the current price of gascoin',
  'where can I check the gascoin price',
  'do I need to hold tokens during the entire review',
  'what if I sell tokens before payout',
  'does selling tokens before payout block my refund',
  'can I hold tokens on an exchange',
  'do tokens need to be in my connected wallet',
  'what if I move tokens to a different wallet',
  'what is the minimum token hold',
  'can I participate with just 1 token',
  'how do I check my tier',
  'where can I see my current tier',
  'does my tier change automatically',
  'when is my tier checked',
  'what if I buy more tokens mid submission',
  'how do I upgrade my tier',
  'is there a tier above fleet',
  'what tier are most users',
  'do I lose my tier if the token price drops',
  'what is the token economy',
  'what is the tokenomics of gascoin',
  'why do I need to hold tokens',
  'what utility does the gascoin token have',
  'is gascoin a meme token',
  'does the token have any governance features',
  'can I stake gascoin tokens',
  'is there a token burn mechanism',
  'what is the market cap of gascoin',
  'how many token holders are there',
  'is there a token vesting schedule',
  'who holds the most gascoin tokens',
  'is there a team allocation of tokens',
  'what dex has the most liquidity for gascoin',
  'how do I add gascoin to my phantom wallet',
  'how do I see my gascoin balance',
  'what is the token ticker symbol',
  'is it GASCOIN or GAS',
  'can I swap other tokens for gascoin',
  'what is slippage when buying gascoin',
  'how do I set slippage on jupiter',

  // ════════════════════════════════════════════════════════════════════════════
  // COOLDOWNS (50)
  // ════════════════════════════════════════════════════════════════════════════
  'how does the cooldown work',
  'what is the cooldown period',
  'how long is the standard cooldown',
  'how long is the commuter cooldown',
  'how long is the road warrior cooldown',
  'how long is the fleet cooldown',
  'is the cooldown per wallet',
  'is the cooldown per x account',
  'can I bypass the cooldown',
  'does using a different wallet reset cooldown',
  'does using a different x account reset cooldown',
  'where do I check my cooldown',
  'what page shows my cooldown timer',
  'what happens if I submit during cooldown',
  'does a failed submission trigger cooldown',
  'does a rejected claim use up my cooldown',
  'does retry later trigger cooldown',
  'when does my cooldown start',
  'does cooldown start at submission or approval',
  'how precise is the cooldown timer',
  'can I see the exact minute my cooldown expires',
  'does upgrading my tier change my active cooldown',
  'what if I submit right when cooldown expires',
  'is there a grace period after cooldown',
  'how many claims can standard tier make per month',
  'how many claims can fleet tier make per month',
  'what is the maximum submissions in a year',
  'can I accumulate unused submissions',
  'does the cooldown count weekends',
  'is the cooldown in calendar days or business days',
  'does the cooldown use utc timezone',
  'what timezone is the cooldown based on',
  'can I see other people\'s cooldowns',
  'why is my cooldown showing wrong',
  'my cooldown says 0 but I still can\'t submit',
  'the cooldown page is not loading',
  'does the cooldown sync between devices',
  'can I get a notification when cooldown expires',
  'is there an email alert for cooldown',
  'does gascoin have push notifications',
  'what is the fastest I can submit again',
  'how does fleet tier submit 4 times per week',
  'does fleet cooldown stack or reset',
  'what if I miss my submission window',
  'does missing a window affect my streak',
  'can I pause my cooldown',
  'is there a way to skip cooldown',
  'do admin users have different cooldowns',
  'does the dev team have shorter cooldowns',
  'has the cooldown ever changed',

  // ════════════════════════════════════════════════════════════════════════════
  // PAYOUTS (70)
  // ════════════════════════════════════════════════════════════════════════════
  'when do I get paid',
  'how long does payout take',
  'what is the typical payout time',
  'what is the maximum payout time',
  'where does the sol go',
  'does sol go to my connected wallet',
  'can I get paid to a different wallet',
  'can I change my payout wallet',
  'how much sol will I receive',
  'how is the refund amount calculated',
  'what determines my refund amount',
  'is there a maximum refund per claim',
  'does the tier affect my refund size',
  'what is the refund cap',
  'why aren\'t exact refund amounts listed',
  'does the sol price affect my refund',
  'can I get paid in usdc instead of sol',
  'can I get paid in a stablecoin',
  'can I get paid in fiat',
  'what if sol price crashes before I sell',
  'where can I sell my sol',
  'how do I convert sol to usd',
  'what exchange should I use to sell sol',
  'can I sell sol on coinbase',
  'can I sell sol on kraken',
  'does gascoin take a fee',
  'are there any hidden fees',
  'what is the transaction fee for payout',
  'who pays the solana transaction fee',
  'what if my payout is pending',
  'my payout says pending queue',
  'what does pending queue mean',
  'how often does the payout queue retry',
  'what if the treasury is empty',
  'does gascoin run out of sol',
  'where does gascoin get the sol for payouts',
  'what is the treasury wallet',
  'how can I verify my payout on chain',
  'what is solscan',
  'how do I find my transaction on solscan',
  'where is the transaction link',
  'what does a successful payout look like',
  'what happens before payout dispatch',
  'what is the pre payout recheck',
  'what does the recheck verify',
  'can my payout be blocked after approval',
  'what would cause a payout to be blocked',
  'does the system recheck my tweet before paying',
  'does the system recheck my token balance before paying',
  'what if I sold my tokens after approval',
  'what if my tweet got deleted before payout',
  'what if my x account went private before payout',
  'what if I unfollowed gazcoinapp before payout',
  'does the payout auto retry',
  'how many times does payout retry',
  'what is the retry interval',
  'can I manually trigger a payout retry',
  'what does status approved mean',
  'what does status paid mean',
  'what does status rejected mean',
  'what does status processing mean',
  'what does status submitted mean',
  'what does status retry_later mean',
  'what does status pending_queue mean',
  'where do I track my payout status',
  'what page shows my payout history',
  'what is the wallet tracker',
  'what is gascoin.app/wallet',
  'does the wallet tracker update in real time',
  'can I see all my past payouts',

  // ════════════════════════════════════════════════════════════════════════════
  // POINTS & STREAKS (60)
  // ════════════════════════════════════════════════════════════════════════════
  'how do points work in gascoin',
  'what can I do with points',
  'do points convert to sol',
  'are points the same as crypto',
  'how many points per approved claim',
  'what is the base points for a claim',
  'how do streak bonuses work',
  'what is a submission streak',
  'how do I maintain my streak',
  'what breaks my streak',
  'what happens if I miss a submission window',
  'how many bonus points for a streak',
  'what is the maximum streak bonus',
  'how many points at streak level 5',
  'do streaks reset if I fail a gate',
  'what are daily holding points',
  'how many daily points for standard tier',
  'how many daily points for commuter tier',
  'how many daily points for road warrior tier',
  'how many daily points for fleet tier',
  'when do daily holding points accrue',
  'do I need to do anything to earn holding points',
  'what are engagement points',
  'how do I earn engagement points',
  'do likes on my tweet earn points',
  'do retweets earn points',
  'do replies earn engagement points',
  'do quote tweets earn points',
  'do bookmarks earn points',
  'how often are engagement points calculated',
  'is there a daily cap on engagement points',
  'is there a monthly cap on engagement points',
  'how does the leaderboard work',
  'what determines leaderboard ranking',
  'is the leaderboard based on points',
  'is the leaderboard based on earnings',
  'what factors weight the leaderboard',
  'where do I see the leaderboard',
  'what is gascoin.app/leaderboard',
  'how often does the leaderboard update',
  'can I see my rank on the leaderboard',
  'what is gascoin.app/points',
  'where do I see my points history',
  'can I transfer points to another user',
  'will points be redeemable for rewards',
  'what is the points roadmap',
  'do points carry over between seasons',
  'what happens to points after season 1',
  'how do referral points work',
  'how many points for a referral',
  'what is the ongoing referral percentage',
  'is there a cap on referral points',
  'how many referral points per month',
  'do I earn points when my referral claims',
  'what is the total points possible per month',
  'who has the most points right now',
  'what is the average points per user',
  'are there any point multiplier events',
  'will there be double points events',
  'does gascoin have promotional point bonuses',

  // ════════════════════════════════════════════════════════════════════════════
  // REFERRALS (50)
  // ════════════════════════════════════════════════════════════════════════════
  'how does the referral program work',
  'how do I get a referral link',
  'where is my referral link',
  'what page shows my referral link',
  'what is gascoin.app/referral',
  'do I need an approved claim to get a referral link',
  'how many people can I refer',
  'is there a limit on referrals',
  'what is the monthly referral cap',
  'how many referrals per 30 days',
  'what do I get for referring someone',
  'how many points for a successful referral',
  'what is the welcome bonus for referrals',
  'do I get sol for referrals or just points',
  'what is the 2 percent ongoing referral',
  'how long does the ongoing referral percentage last',
  'is the 2 percent calculated monthly',
  'what is the monthly cap on referral points',
  'can I refer myself',
  'is self referral detected',
  'can I refer someone with the same ip',
  'what is referral ring detection',
  'what happens if referral fraud is detected',
  'can I refer my friend',
  'can I share my referral link on social media',
  'can I post my referral link on youtube',
  'when does my referral get credited',
  'how long until the referral bonus shows',
  'does the referred person need to get approved first',
  'does the referred wallet need to be 7 days old',
  'what is the 7 day wallet age requirement',
  'can I see who I referred',
  'is there a referral dashboard',
  'can I track my referral earnings',
  'how do I share my referral link',
  'what format is the referral link',
  'can I customize my referral link',
  'do referral links expire',
  'what happens if my referral link stops working',
  'can I have multiple referral links',
  'does the referral system work globally',
  'are there referral leaderboards',
  'who has the most referrals',
  'is there a referral tier system',
  'do top referrers get special perks',
  'what is the maximum referral earnings per month',
  'can I earn referral points from indirect referrals',
  'is the referral tree multi level',
  'what prevents referral abuse',
  'how does gascoin prevent referral manipulation',

  // ════════════════════════════════════════════════════════════════════════════
  // TROUBLESHOOTING (100)
  // ════════════════════════════════════════════════════════════════════════════
  'my wallet won\'t connect',
  'phantom wallet not connecting',
  'solflare wallet not connecting',
  'backpack wallet not connecting',
  'the connect button does nothing',
  'wallet connection times out',
  'I get an error when connecting wallet',
  'wrong wallet connected',
  'how do I disconnect my wallet',
  'can I switch wallets after connecting',
  'my x login failed',
  'privy login not working',
  'the sign in button is grayed out',
  'I can\'t sign in with twitter',
  'it says my account is not eligible',
  'I get redirected to a blank page after login',
  'my submission is stuck on step 3',
  'the upload button is not working',
  'my photo won\'t upload',
  'the file is too large to upload',
  'the form says invalid tweet url',
  'it can\'t find my tweet',
  'the tweet url I pasted doesn\'t work',
  'what format should the tweet url be',
  'my submission has been processing for over an hour',
  'is there a processing backlog',
  'are the servers down right now',
  'is gascoin having issues today',
  'where can I check the system status',
  'the website is loading slowly',
  'the page keeps refreshing',
  'I see a blank white page',
  'the css is broken on the website',
  'the website looks different on my phone',
  'I can\'t see the chat agent',
  'the chat agent is not responding',
  'the chat agent gave me wrong information',
  'I just followed gazcoinapp but gate 2 fails',
  'how long after following does the cache refresh',
  'gate 2 keeps failing even though I follow',
  'my receipt keeps failing ocr',
  'the ocr read the wrong amount',
  'the ocr can\'t find my wallet characters',
  'the ocr can\'t find the hashtag on my receipt',
  'gate 10 keeps failing',
  'I wrote clearly but gate 10 still fails',
  'tips to pass gate 10 consistently',
  'my receipt is clear but gate 9 fails',
  'the ai thinks my receipt is fake',
  'false positive on gate 12',
  'gate 13 says my receipt is tampered but it\'s not',
  'the amount I entered doesn\'t match',
  'what tolerance does gate 16 allow',
  'my claim got rejected but I followed all the rules',
  'can I appeal a rejected claim',
  'how do I dispute a gate failure',
  'is there a human review option',
  'I got approved but haven\'t received sol',
  'my payout has been pending for 24 hours',
  'my payout has been pending for 48 hours',
  'status shows approved but no transaction',
  'the transaction link doesn\'t work',
  'I received less sol than expected',
  'the sol amount seems wrong',
  'I got banned from gascoin',
  'how do I appeal a ban',
  'what causes an automatic ban',
  'can a ban be reversed',
  'my account was flagged',
  'what does account flagged mean',
  'my checkmark disappeared',
  'my x premium expired during processing',
  'I renewed x premium but gate 1 still fails',
  'my follower count dropped below 100',
  'I lost followers and now gate 4 fails',
  'my cooldown timer seems wrong',
  'the cooldown shows negative hours',
  'the cooldown page won\'t load',
  'I can\'t see my claim history',
  'the wallet tracker is empty',
  'my previous claims don\'t show up',
  'the gate results page is blank',
  'none of the gates show results',
  'the page is stuck on loading',
  'I get a 404 error on the site',
  'I get a 500 error on the site',
  'I get a rate limit error',
  'it says too many requests',
  'the submit button is disabled',
  'I can\'t click submit',
  'my browser doesn\'t support the site',
  'does gascoin work with safari',
  'does gascoin work with firefox',
  'does gascoin work with brave browser',
  'my adblocker is blocking gascoin',
  'should I disable my vpn for gascoin',
  'does gascoin work behind a vpn',
  'my previous claim shows retry later',
  'what does retry later mean',
  'does retry later count against my cooldown',
  'when should I retry after retry later',

  // ════════════════════════════════════════════════════════════════════════════
  // SECURITY & PRIVACY (40)
  // ════════════════════════════════════════════════════════════════════════════
  'is my personal information safe',
  'what data does gascoin collect',
  'does gascoin store my receipt permanently',
  'when is receipt data deleted',
  'what is the data retention policy',
  'does gascoin see my credit card number',
  'does gascoin see my name on the receipt',
  'does gascoin see my address',
  'what does gemini extract from my receipt',
  'does gascoin store my x password',
  'how does privy authentication work',
  'is privy secure',
  'can gascoin access my x dm\'s',
  'can gascoin post tweets on my behalf',
  'does gascoin store my wallet private key',
  'can gascoin withdraw from my wallet',
  'is the smart contract audited',
  'is there a smart contract',
  'where can I verify the payout transaction',
  'how do I know the payout is real',
  'what prevents gascoin from stealing funds',
  'who controls the treasury wallet',
  'is the treasury multisig',
  'what fraud prevention does gascoin use',
  'how does gascoin prevent fake receipts',
  'how does gascoin prevent duplicate submissions',
  'how does gascoin detect ai generated images',
  'can someone else claim my receipt',
  'what if someone photographs my receipt',
  'what if someone steals my tweet',
  'is there two factor authentication',
  'can I delete my gascoin account',
  'how do I request data deletion',
  'is gascoin gdpr compliant',
  'does gascoin sell my data',
  'are my submissions public',
  'can other users see my claims',
  'what is the community feed',
  'does the community feed show my wallet address',
  'can I opt out of the community feed',

  // ════════════════════════════════════════════════════════════════════════════
  // PLATFORM PAGES (50)
  // ════════════════════════════════════════════════════════════════════════════
  'what pages does gascoin have',
  'what is gascoin.app/submit',
  'what is gascoin.app/wallet',
  'what is gascoin.app/how-it-works',
  'what is gascoin.app/gates',
  'what is gascoin.app/docs',
  'what is gascoin.app/leaderboard',
  'what is gascoin.app/referral',
  'what is gascoin.app/perks',
  'what is gascoin.app/community',
  'what is gascoin.app/points',
  'what is gascoin.app/welcome',
  'where do I submit a claim',
  'where do I check my status',
  'where do I see my points',
  'where do I see the leaderboard',
  'where do I find my referral link',
  'where is the documentation',
  'what does the gates page show',
  'what does the perks page show',
  'what is the community feed',
  'does the community feed show real claims',
  'what information is on the community feed',
  'can I see other users claims',
  'what does the wallet tracker show',
  'does the wallet tracker show all my claims',
  'can I see gate results for past claims',
  'how do I use the pre flight checklist',
  'what is the pre flight checklist',
  'where is the pre flight checklist',
  'does the gates page update in real time',
  'are the pass rates on the gates page real',
  'how accurate are the gate statistics',
  'what does the how it works page show',
  'is there a step by step visual guide',
  'how many steps does the how it works page show',
  'does the docs page cover everything',
  'how often is the documentation updated',
  'is the documentation generated from code',
  'where can I provide feedback on the site',
  'is there a discord or telegram',
  'how do I contact the team',
  'who runs gascoin',
  'what is gascoin.app',
  'is gascoin.app the official website',
  'are there any other official gascoin websites',
  'does gascoin have social media accounts',
  'what is @GasCoinApp on twitter',
  'how do I follow gascoin on x',
  'does gascoin have a newsletter',

  // ════════════════════════════════════════════════════════════════════════════
  // CRYPTO BASICS (40)
  // ════════════════════════════════════════════════════════════════════════════
  'what is sol',
  'what is solana',
  'is sol real money',
  'how do I convert sol to cash',
  'where can I sell sol',
  'what exchanges support sol',
  'what is a crypto wallet',
  'what is a solana wallet',
  'is phantom wallet safe',
  'is solflare wallet safe',
  'is backpack wallet safe',
  'what are transaction fees on solana',
  'do I pay gas fees to receive sol',
  'how fast are solana transactions',
  'what is a blockchain',
  'what is an spl token',
  'what is a dex',
  'what is jupiter exchange',
  'what is raydium',
  'how do I swap tokens on jupiter',
  'what is slippage in crypto',
  'what is a token address',
  'how do I add a custom token to phantom',
  'what is a wallet address vs private key',
  'can I recover my wallet if I lose my seed phrase',
  'what if I send sol to the wrong address',
  'are solana transactions reversible',
  'what is solscan',
  'how do I use solscan to verify a transaction',
  'what does a solana transaction look like',
  'how long does a solana transfer take',
  'what is the current sol price',
  'does sol price affect my refund value',
  'what is market cap',
  'what is a liquidity pool',
  'what is defi',
  'is gascoin defi',
  'what network is gascoin on',
  'do I need sol in my wallet to receive gascoin',
  'what is rent on solana',

  // ════════════════════════════════════════════════════════════════════════════
  // COMPARISONS & GENERAL (30)
  // ════════════════════════════════════════════════════════════════════════════
  'how is gascoin different from cashback apps',
  'how is gascoin different from getupside',
  'how is gascoin different from gas buddy',
  'why sol instead of usd',
  'why does gascoin use crypto',
  'why solana instead of ethereum',
  'why not use bitcoin',
  'what makes gascoin unique',
  'is gascoin the only gas refund crypto project',
  'are there competitors to gascoin',
  'what is the business model',
  'how does gascoin make money',
  'who created gascoin',
  'who is behind gascoin',
  'is there a team page',
  'is gascoin open source',
  'is the code on github',
  'when was gascoin created',
  'what is the roadmap',
  'what comes after season 1',
  'will there be a season 2',
  'what new features are planned',
  'will gascoin expand to other expenses',
  'will gascoin ever refund diesel',
  'will gascoin work with ev charging in the future',
  'is gascoin a dao',
  'do token holders get voting rights',
  'what is the long term vision',
  'will gascoin be available on other chains',
  'is gascoin planning an airdrop',
];

export default QUESTIONS_1000;
